[phases.setup]
nixpkgs = [
  "nodejs_18",
  "chromium",
  "libnss3",
  "libatk1.0",
  "libatk-bridge2.0",
  "libcups",
  "libgbm",
  "libasound2",
  "libpangocairo",
  "libxss1",
  "libgtk-3",
  "libxshmfence",
  "libglu1"
]

[phases.install]
cmds = ["npm install"]

[phases.start]
cmd = "node app.js"
